services:
  aws-cli:
    build: .
    container_name: aws-toolbox
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "8081:8081"
    # volumes:
    #   - ./config:/app/config
